spring:
  config:
    import:
    - dbsettings.properties
    - kakaosettings.properties
    - jwtsettings.properties
  server:
    address: localhost
    port: 8080
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${db.password}
    url: ${db.url}
    username: ${db.user}
  jpa:
    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
      jakarta:
        persistence:
          persistence-unit-name: jpa-test
    generate-ddl: true
    show-sql: true

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    operations-sorter: alpha # alpha(알파벳 오름차순), method(HTTP메소드순)
    tags-sorter: alpha # 태그 정렬 기준
    path: /swagger-ui.html # html 문서 접속 경로
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: none # tag, operation 펼치는 방식
  paths-to-match:
    - /**

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace


kakao:
  CLIENT_SECRET: p9iuf6DDf3WydhBHR9YwnDWOngEmo
  REST_API_KEY: 223392a6512c6867ae141bab90e937f2
  REDIRECT_URI: http://13.125.118.115:8080/oauth/kakao

paldojwt:
  ISSUER_SECRET: "paldo_lavin"


